version: "2"
services:
  consumer:
    build:
      context: ../
      dockerfile: ./dockerfiles/consumer.Dockerfile
    tty: true
  producer:
    build:
      context: ../
      dockerfile: ./dockerfiles/producer.Dockerfile
    ports:
      - "9092:9092"
    tty: true
