version: "2"
services:
  consumer:
    build:
      context: ../
      dockerfile: ./consumer/Dockerfile
    tty: true
  producer:
    build:
      context: ../
      dockerfile: ./producer/Dockerfile
    ports:
      - "9092:9092"
    tty: true
