apiVersion: v1
kind: Pod
metadata:
  name: kafka-cluster
  labels:
    app: kcluster
spec:
  containers:
    - name: zookeeper
      imagePullPolicy: Never
      image: image-zookeeper
      tty: true
      ports:
        - containerPort: 2181
    - name: broker
      imagePullPolicy: Never
      image: image-broker
      tty: true
      ports:
        - containerPort: 9092
    - name: consumer
      imagePullPolicy: Never
      image: image-consumer
      tty: true
    - name: producer
      imagePullPolicy: Never
      image: image-producer
      tty: true
      
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: broker
      port: 9092
      targetPort: 9092
  selector:
    app: kcluster
  type: ClusterIP