apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-cluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      restartPolicy: Always
      containers:
        - name: zookeeper
          image: thecsmine/sdtd:zookeeper
          tty: true
          ports:
            - containerPort: 2181
        - name: kafka
          image: thecsmine/sdtd:kafka
          tty: true
        - name: consumer
          image: thecsmine/sdtd:consumer
          tty: true
        - name: producer
          image: thecsmine/sdtd:producer
          tty: true
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181
    - name: producer
      port: 9092
      targetPort: 9092
  selector:
    app: kafka-service 
