apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kzookeeper
  template:
    metadata:
      labels:
        app: kzookeeper
    spec:
      restartPolicy: No
      containers:
        - name: zookeeper
          imagePullPolicy: Always
          image: thecsmine/sdtd:zookeeper
          tty: true
          ports:
            - containerPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbroker
  template:
    metadata:
      labels:
        app: kbroker
    spec:
      restartPolicy: No
      containers:
        - name: broker
          imagePullPolicy: Always
          image: thecsmine/sdtd:broker
          tty: true
          ports:
            - containerPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kconsumer
  template:
    metadata:
      labels:
        app: kconsumer
    spec:
      restartPolicy: No
      containers:
        - name: consumer
          imagePullPolicy: Always
          image: thecsmine/sdtd:consumer
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kproducer
  template:
    metadata:
      labels:
        app: kproducer
    spec:
      restartPolicy: No
      containers:
        - name: producer
          imagePullPolicy: Always
          image: thecsmine/sdtd:producer
          tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: kzookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kbroker