apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kzookeeper
  template:
    metadata:
      labels:
        app: kzookeeper
    spec:
      containers:
        - name: zookeeper
          imagePullPolicy: Always
          image: thecsmine/sdtd:zookeeper
          tty: true
          ports:
            - containerPort: 2181
            - containerPort: 2182
          resources:
            limits:
              ephemeral-storage: "1000Mi"
          volumeMounts:
            - name: zookeeper-volume
              mountPath: /tmp/zookeeper
      volumes:
        - name: zookeeper-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbroker
  template:
    metadata:
      labels:
        app: kbroker
    spec:
      containers:
        - name: broker
          imagePullPolicy: Always
          image: thecsmine/sdtd:broker
          tty: true
          ports:
            - containerPort: 9092
          resources:
            limits:
              ephemeral-storage: "1000Mi"
          volumeMounts:
            - name: broker-volume
              mountPath: /tmp/kafka-logs
      volumes:
        - name: broker-volume
          emptyDir: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kproducer
  template:
    metadata:
      labels:
        app: kproducer
    spec:
      containers:
        - name: producer
          imagePullPolicy: Always
          image: thecsmine/sdtd:producer
          tty: true
          resources:
            limits:
              ephemeral-storage: "1000Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kconsumer
  template:
    metadata:
      labels:
        app: kconsumer
    spec:
      containers:
        - name: consumer
          imagePullPolicy: Always
          image: thecsmine/sdtd:consumer
          tty: true
          resources:
            limits:
              ephemeral-storage: "1000Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-stats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kstats
  template:
    metadata:
      labels:
        app: kstats
    spec:
      containers:
        - name: stats-consumer
          imagePullPolicy: Always
          image: thecsmine/sdtd:stats_consumer
          tty: true
          resources:
            limits:
              ephemeral-storage: "1000Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - name: zookeeper
      port: 2181
      protocol: TCP
      targetPort: 2181
    - name: zookeeper-admin
      port: 2182
      protocol: TCP
      targetPort: 2182
      nodePort: 32182
  selector:
    app: kzookeeper
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
    - port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kbroker
  type: NodePort