apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kzookeeper
  template:
    metadata:
      labels:
        app: kzookeeper
    spec:
      containers:
        - name: zookeeper
          imagePullPolicy: Always
          image: thecsmine/sdtd:zookeeper
          resources:
            requests:
              cpu: "0.1"
              ephemeral-storage: "100Mi"
              memory: "64Mi"
            limits:
              cpu: "0.3"
              ephemeral-storage: "600Mi"
              memory: "128Mi"
          tty: true
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /tmp/zookeeper/
              name: zookeeper-volume
      volumes:
        - name: zookeeper-volume
          emptyDir:
            sizeLimit: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbroker
  template:
    metadata:
      labels:
        app: kbroker
    spec:
      containers:
        - name: broker
          imagePullPolicy: Always
          image: thecsmine/sdtd:broker
          resources:
            requests:
              cpu: "0.1"
              ephemeral-storage: "100Mi"
              memory: "64Mi"
            limits:
              cpu: "0.3"
              ephemeral-storage: "600Mi"
              memory: "128Mi"
          tty: true
          ports:
            - containerPort: 9092
          volumeMounts:
            - mountPath: /tmp/kafka-logs/
              name: broker-volume
      volumes:
        - name: broker-volume
          emptyDir:
            sizeLimit: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kconsumer
  template:
    metadata:
      labels:
        app: kconsumer
    spec:
      containers:
        - name: consumer
          imagePullPolicy: Always
          image: thecsmine/sdtd:consumer
          resources:
            requests:
              cpu: "0.1"
              ephemeral-storage: "100Mi"
              memory: "64Mi"
            limits:
              cpu: "0.3"
              ephemeral-storage: "600Mi"
              memory: "128Mi"
          tty: true
          volumeMounts:
            - mountPath: /tmp/
              name: consumer-volume
      volumes:
        - name: consumer-volume
          emptyDir:
            sizeLimit: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kproducer
  template:
    metadata:
      labels:
        app: kproducer
    spec:
      containers:
        - name: producer
          imagePullPolicy: Always
          image: thecsmine/sdtd:producer
          resources:
            requests:
              cpu: "0.1"
              ephemeral-storage: "100Mi"
              memory: "64Mi"
            limits:
              cpu: "0.3"
              ephemeral-storage: "600Mi"
              memory: "128Mi"
          tty: true
          volumeMounts:
            - mountPath: /tmp/
              name: producer-volume
      volumes:
        - name: producer-volume
          emptyDir:
            sizeLimit: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: kzookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kbroker
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "0.4"
    requests.memory: 64Mi
    requests.ephemeral-storage: 400Mi
    limits.cpu: "1"
    limits.memory: 512Mi
    limits.ephemeral-storage: 3Gi