apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kzookeeper
  template:
    metadata:
      labels:
        app: kzookeeper
    spec:
#      restartPolicy: Always
      containers:
        - name: zookeeper
          imagePullPolicy: Always
          image: thecsmine/sdtd:zookeeper
          resources:
            requests:
              cpu: "500m"
              ephemeral-storage: "2Gi"
              memory: "1Gi"
            limits:
              cpu: "500m"
              ephemeral-storage: "2Gi"
              memory: "1Gi"
          tty: true
          ports:
            - containerPort: 2181
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-broker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kbroker
  template:
    metadata:
      labels:
        app: kbroker
    spec:
#      restartPolicy: Always
      containers:
        - name: broker
          imagePullPolicy: Always
          image: thecsmine/sdtd:broker
          resources:
            requests:
              cpu: "500m"
              ephemeral-storage: "500Mi"
              memory: "1Gi"
            limits:
              cpu: "500m"
              ephemeral-storage: "1000Mi"
              memory: "1Gi"
          tty: true
          ports:
            - containerPort: 9092
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kconsumer
  template:
    metadata:
      labels:
        app: kconsumer
    spec:
#      restartPolicy: Always
      containers:
        - name: consumer
          imagePullPolicy: Always
          image: thecsmine/sdtd:consumer
          resources:
            requests:
              cpu: "500m"
              ephemeral-storage: "500Mi"
              memory: "1Gi"
            limits:
              cpu: "500m"
              ephemeral-storage: "1000Mi"
              memory: "1Gi"
          tty: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kproducer
  template:
    metadata:
      labels:
        app: kproducer
    spec:
#      restartPolicy: Always
      containers:
        - name: producer
          imagePullPolicy: Always
          image: thecsmine/sdtd:producer
          resources:
            requests:
              cpu: "500m"
              ephemeral-storage: "500Mi"
              memory: "1Gi"
            limits:
              cpu: "500m"
              ephemeral-storage: "1000Mi"
              memory: "1Gi"
          tty: true
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      targetPort: 2181
  selector:
    app: kzookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  labels:
    app: broker
spec:
  ports:
    - port: 9092
      targetPort: 9092
  selector:
    app: kbroker
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 1Gi
    requests.ephemeral-storage: 8Gi
    limits.cpu: "2"
    limits.memory: 2Gi
    limits.ephemeral-storage: 8Gi
